#!/usr/bin/env python
# -*- coding:utf-8 -*-

import rospy
import math
from ublox_msgs.msg         import NavRELPOSNED

def publisher():
      
    DataN = 1  # m
    DataE = -1 # m
    
    navrelposned = NavRELPOSNED()
    navrelposned.relPosN = DataN * 100
    navrelposned.relPosE = DataE * 100
    navrelposned.flags = 23

    out_topic_name = "/ublox_gps/navrelposned"
    gps_pub = rospy.Publisher(out_topic_name, NavRELPOSNED, queue_size=10)

    rate = rospy.Rate(10)
    while not rospy.is_shutdown():
        gps_pub.publish(navrelposned)
        rate.sleep()

if __name__ == '__main__':
  rospy.init_node('manual_rtk_pub', anonymous=True)
  try:
    publisher()
    rospy.spin()
  except rospy.ROSInterruptException:
    rospy.loginfo("manual_rtk_pub node finished.")
